### ISSUE TITLE
Can you please make this package compatible with Angular 16.x?

### ISSUE THREAD

**Issue by sudhakars4tf** [ebenefits/odata-v4-ng#30]
Firstly, I really appreciate you maintaining this project alive with the upcoming angular versions. 

A Big Thank You!

**Issue:**
When I try to install this package using npm in an Angular 16.2.0 application project, I am getting the following message:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: angular-test2@0.0.0
npm ERR! Found: @angular/common@16.2.2
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^16.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.0.0" from @ebenefitsbv/odata-v4-ng@15.0.1
npm ERR! node_modules/@ebenefitsbv/odata-v4-ng
npm ERR!   @ebenefitsbv/odata-v4-ng@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Can you please make this package compatible with Angular 16.x?

**Comment by kees-wiegel-visma** [comment]
Hey @sudhakars4tf I'm so sorry for not seeing your issue earlier! I have no clue why nobody got any notifications about this new issue. Feel free to ping me next time something like this happens :)

We will make versions for angular 16.x and 17.x available this week!

**Comment by kees-wiegel-visma** [comment]
Angular 16 PR created!

**Comment by kees-wiegel-visma** [comment]
Now also compatible with Angular 17 and 18 :)
